services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: sb-server
    ports:
      - "8080:8080"
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
